version: "3.3"
services:
  app:
    build: .
    command: /app/bin/entrypoint.sh --wait --migrate --dev
    container_name: jogging-service
    environment:
      - DEVELOPMENT=1
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgrespass
      - APPLICATION_PORT=8000
      - APPLICATION_WORKERS=3
      - ENV=dev
    depends_on:
      - db
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ./:/app

  db:
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespass