"""run weather

Revision ID: 94d079cf6bc3
Revises: 8ae60b5e9f5e
Create Date: 2021-08-15 15:02:01.211197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94d079cf6bc3'
down_revision = '8ae60b5e9f5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('weather', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'weather')
    # ### end Alembic commands ###
